#!/bin/bash

err(){
    echo -e "\e[1;31mE: $* \e[0m" >> /dev/stderr
}

TO_LAUNCH=$1

if [[ $TO_LAUNCH == "run" ]]
then
    PATH_TO_DB=${2:-data/students.bin}
    FLAG=$3
    QUERIES=$4
    #soit le fichier existe
    if [[ -f "$PATH_TO_DB" ]]
    then
        if [[ $QUERIES == "" ]]
        then
            if [[ $FLAG == "-f" ]]
            then
                err "Le fichier de requêtes n'existe pas"
            fi
            set -m
            ./tinydb $PATH_TO_DB &
            echo "PID=$!"
            fg
        else
            if [[ -f $QUERIES ]]
            then
                set -m
                ./tinydb $PATH_TO_DB  < $QUERIES &
                echo "PID=$!"
                fg
            else
                err "Le fichier de requêtes n'existe pas"
            fi
        fi
    else
        #soit le fichier n'existe pas
        mkdir data
        touch $PATH_TO_DB
        err "Le chemin vers la base de données n'existe pas"
    fi
elif [[ $TO_LAUNCH == "status" ]]
then
    INSTANCE_COUNT=$(pgrep tinydb -c)
    #On a le nombre total d'instances en cours, il faut enlever les fils de chaque père
    INSTANCE_COUNT=$((INSTANCE_COUNT/5))
    echo "$INSTANCE_COUNT instance(s) running"
    ALL_INSTANCES=$(pgrep tinydb)
    #Compteur pour voir si on est sur un fils ou un père
    COUNT=0
    for pid in $ALL_INSTANCES
    do
        if ! ((COUNT % 5))
        then
            echo -e "  > PID $pid"
        fi
        COUNT=$((COUNT+1))
    done
elif [[ $TO_LAUNCH == "sync" ]]
then
    INSTANCE_COUNT=$(pgrep tinydb -c)
    echo "Found $((INSTANCE_COUNT/5)) instance(s) of tinydb"
    ALL_INSTANCES=$(pgrep tinydb)
    COUNT=0
    for pid in $ALL_INSTANCES
    do
        if ! ((COUNT % 5))
        then
            echo "  Sync process $pid..."
            kill -SIGUSR1 $pid
        fi
        COUNT=$((COUNT+1))
    done
    echo "Done"
elif [[ $TO_LAUNCH == "shutdown" ]]
then
    PID=$2
    ALL_INSTANCES=$(pgrep tinydb)
    INSTANCE_COUNT=$(pgrep tinydb -c)
    COUNT=0
    if [[ $PID == "" ]]
    then
        #on devra demander pour chaque pid père si on veut le shutdown
        for pid in $ALL_INSTANCES
        do
            if ! ((COUNT%5))
            then
                #si c'est un processus principal
                read -p "Voulez-vous terminer le processus $pid? (y/n) : " choice

                if [[ $choice == "y" ]]
                then
                    #si on veut supprimer le supprimer le père, on doit incrémenter le compteur
                    #de 5 afin de "passer" ses fils
                    pid=$((pid-1))
                    kill -- -$pid
                fi  
            fi
            COUNT=$((COUNT+1))
        done
    else
        found=false
        for pid in $ALL_INSTANCES
        do
            if ! ((COUNT % 5))
            then
                if [[ $pid == $PID ]]
                then
                    #si c'est un processus principal on kill le groupe associé
                    PID=$((PID-1))
                    kill -- -$PID
                    found=true
                    break
                fi
            fi
            COUNT=$((COUNT+1))
        done
        if [[ $found == false ]]
        then
            err "Le pid donné n'existe pas ou n'est pas celui d'un processus principal"
        fi
    fi
else
    err "Mauvaise utilisation!\nUtilisez : './monitoring <opt> [chemin_vers_db] [-f fichier_requetes]'\n<opt>=run|status|sync|shutdown\nLes crochets signifient que les arguments sont optionnels."
fi